### ISSUE TITLE
Allow overriding default renderer's "icons"

### ISSUE THREAD

**Issue by realStandal** [listr2/listr2#613]
I'm wanting to override the "icons" used by the `DefaultRenderer` (the glyphs provided by `figures`). The defaults don't fit others in my project, and I'm all for consistency.

I've gotten by being able to extend the DefaultRenderer then override the `getSymbol` method. TypeScript complains (changing that method's type to `protected` would fix that error) - but I know the compiled JavaScript is ok.

It'd be even cooler to have a dedicated configuration option. From a quick look at the source, maybe just to overwrite `figures` and then use the defaults if no value is given?

**Comment by cenk1cenk2** [comment]
This looks like a good idea for having consistent projects. I would really like that, I might give it a go this weekend but these days I am pretty swamped with other projects.

**Comment by cenk1cenk2** [comment]
Please check out the new feature of overriding the style [here](https://listr2.kilic.dev/renderer/logger.html#icons-and-colors). I suppose this is a bit more complicated than what you initially requested but for consistency, I have not found a better solution for consistency.

This is mainly finalized from my side so I do not think I will make more improvements over it through the comments.

This is currently only available in beta but should be merged upstream soon.
