### ISSUE TITLE
Feature request: showTimer only for sufficiently long tasks?

### ISSUE THREAD

**Issue by starpit** [listr2/listr2#646]
It would be nice to do something similar to mocha and other testing rigs, in distinguishing long- and short-running tasks. Right now `listr2` always adds the timer, if `showTimer: true`

Suggestion: allow the `showTimer` value to be a number, which indicates the threshold below which the timer will not be shown.

Stretch goal: allow levels of timers: < level1 no output; < level 2 chalk.dim; < level 3 chalk.yellow; else chalk.red

**Comment by cenk1cenk2** [comment]
It can be done through making showTimer a boolean or a function that takes in a current task time as parameter or smt like that. This can be added to the default.renderer.ts file.

But unfortunetly these days for me are pretty busy and it has been like that for a while so I would close the open issues before adding any new features but would glady accept a pull request if you have time to give it a try.

**Comment by starpit** [comment]
Ok great, i may look into it over the weekend

**Comment by cenk1cenk2** [comment]
Please checkout the new presets that can conditionally enable timers or timestamps [here](https://listr2.kilic.dev/renderer/logger.html#presets).

This is mainly finalized from my side so I do not think I will make more improvements over it through the comments.
