### ISSUE TITLE
Beta version documentation

### ISSUE THREAD

**Issue by techquestions** [listr2/listr2#667]
Recently the v6 beta version has been release.

Is there any documentation or migration guide for this version? 
Are there any plans on updating documentation on the `beta` branch?

**Comment by cenk1cenk2** [comment]
The short answer is not yet. I might provide a migration guide as markdown if I will test/merge this to upstream branch soon.

But the website documentation is pretty much have to be rewritten due to dropped support on the things I was using before so that will also eventually happen.

**Comment by cenk1cenk2** [comment]
Please check out the migration guide to v6 from [here](https://listr2.kilic.dev/migration/v6.html#migration). Most of the cases should be covered.
