### ISSUE TITLE
Feature request: retry delay

### ISSUE THREAD

**Issue by no2chem** [listr2/listr2#668]
Hi there, 

Great project - I'm really enjoying using listr2 so far (only used it for a few days but really cleaned up some existing boiler plate code).

However, when I write a task that can be retried, I find myself writing this boiler plate code over and over again:

```typescript
        task: async (ctx, task) => {
            if (task.isRetrying()) {
                await delay(1000);
            }
            
            // code here
        },
```

I have to imagine this is a pretty common use case with retry. I'd be happy to open a PR which tries to add a `retryDelay` feature (and maybe potentially add something to the renderer?)

**Comment by cenk1cenk2** [comment]
Yeah pretty doable. I can make the retry optionally as an object where you can pass count and delay in between.

I will try to add this whenever I find time to finalize the beta version.

**Comment by cenk1cenk2** [comment]
Please check out the related section in the documentation [here](https://listr2.kilic.dev/task/retry.html#retry-delay). This is currently only available through the beta version, but will be finalized soon if there is no other input.
