### ISSUE TITLE
[Bug]: ProcessOutput Releases w/o Line Breaks

### ISSUE THREAD

**Issue by straub** [listr2/listr2#670]
### Replication of the Problem

```js
const { Listr } = require('listr2');

const tasks = new Listr({
  task: () => {
    console.log('one');
    console.log('two');
  },
})

tasks.run();
// Outputs "onetwo"
```

### Problem

Hi there,

I'm trying to use Listr2@6 in my CLI, but when tasks have console output, line breaks are lost during `release()`. The output comes out all glued together in one line, which is difficult to read.

(Also, is there a way to opt out of output during release? I'd prefer to hide it entirely, but I couldn't see a related option in the docs / source.)

Let me know if you need further details!

### Environment

MacOS Ventura 13.2.1
Node.js 16.20.0
iTerm2 3.4.19
listr2@6.0.3

### Log Output

```bash
onetwo
```

### Preflight

- [X] Read/Search existing issues and the provided [documentation](https://listr2.kilic.dev).
- [X] Be sure to not open an issue in the [looking for contributions section](/repository/contributions.html#looking-for-contributions).
- [X] Checking the latest version of the software to confirm it has not been fixed already.

**Comment by straub** [comment]
Please don't rush on my account. Feel better soon!

**Comment by straub** [comment]
6.2 resolved my issues! Streams are releasing with no extra blank lines :)

I'm using `new ProcessOutput(null, null, { dump: [] })` rather than my custom subclass now. Thanks again!

**Comment by cenk1cenk2** [comment]
No problems at all. I am glad it was a quick fix for you and thank you again for reporting the issue.

Have a very nice day!
