### ISSUE TITLE
[Feature]: Do not render the followup (future) tasks during execution and in case of an error

### ISSUE THREAD

**Issue by chetzof** [listr2/listr2#679]
### Feature Request

I'm trying to create a lazy version of the Default Renderer, that renders the tasks as they progress. 
![CleanShot 2023-05-18 at 13 57 18@2x](https://github.com/listr2/listr2/assets/467230/8b73292c-9f4d-4ee6-93af-acc57bcd17bc)

I've managed to do this by adding the new task dynamically to the Task Manager as soon as previous one finishes successfully...but that's not the most elegant solution...

P.S. I'm a silent yet grateful user of your package and included it in a lot of internal projects. Thanks for the great work!

### Use Case

I need to recreate a bootstrap wizard similar to `npm create astro@latest` and I've noticed that if even if the 2nd step fails, the 3rd, 4th,.... steps are rendered and make it harder to parse visually the output.

### Contribution

- [ ] I can implement this feature without anything else required, when specification finalizes.
- [X] I can implement this feature with guidence.
- [X] It is just a request.

### Preflight

- [X] Read/Search existing issues and the provided [documentation](https://listr2.kilic.dev).
- [X] Be sure to not open an issue in the [looking for contributions section](/repository/contributions.html#looking-for-contributions).
- [X] Checking the latest version of the software to confirm it has not been added already.

**Comment by cenk1cenk2** [comment]
Hey @chetzof,

Thanks for the kind words. I will be away for couple of days. You can somewhat achieve this behavior through not giving the task a title initially and assigning it a title when the task starts.

Give this one try https://listr2.kilic.dev/task/title.html#tasks-without-a-title to see whether it captures the behavior you wish.

**Comment by chetzof** [comment]
Thanks, with some refactoring that pretty much solves the issue for me. 
Up to you whether it makes sense to have a dedicated global option for that and the issue can be closed if not. 

Thanks again!

**Comment by cenk1cenk2** [comment]
Cool, no problem. I will close the issue for now but keep that in mind.
