### ISSUE TITLE
[Bug]: disableColor option is ignored

### ISSUE THREAD

**Issue by teppeis** [listr2/listr2#687]
### Replication of the Problem

```js
import { Listr } from "listr2";

new Listr(
  [
    {
      title: "foo",
      task: (ctx, task) => {
        task.output = "bar";
      },
    },
  ],
  { disableColor: true },
).run();
```

### Problem

Even if `disableColor` option of `listr` is enabled, it is ignored and the output is colored.
The reason is that `createColors({ useColor: !process.env["LISTR_DISABLE_COLOR"]})` is called before evaluating `disableColor`.

### Environment

- macOS Ventura
- Node.js: v20.5.1
- listr2: v4.2.0

### Preflight

- [X] Read/Search existing issues and the provided [documentation](https://listr2.kilic.dev).
- [X] Be sure to not open an issue in the [looking for contributions section](/repository/contributions.html#looking-for-contributions).
- [X] Checking the latest version of the software to confirm it has not been fixed already.

**Comment by cenk1cenk2** [comment]
Dear @teppeis,

This will be fixed on the next release and any option that uses this environment variable functionality is also not working properly, so I have to rethink how we can save this without doing a breaking change and turning the color into a function that gets called while listr class is constructing.

**Comment by cenk1cenk2** [comment]
No problem, thank you very much for reporting this.

It is always these "cute" things that I have not tested properly causes some problems :D
