### ISSUE TITLE
[Bug]: Documentation site broken

### ISSUE THREAD

**Issue by Deester4x4jr** [listr2/listr2#688]
### Replication of the Problem

- Visit https://listr2.kilic.dev/api and observe a 404
- Visit https://listr2.kilic.dev/renderer/test.html and expand the `Details` dropdown to observe a `File not found` message

### Problem

The documentation site seems to be a little broken. Lots of 404's or `File not found` messages in code examples. Just thought you might like to know.

### Environment

OSX Ventura: 13.2.1 (22D68)
Chrome latest

Probably anyone viewing the site

### Log Output

```bash
N/A
```

### Preflight

- [X] Read/Search existing issues and the provided [documentation](https://listr2.kilic.dev).
- [X] Be sure to not open an issue in the [looking for contributions section](/repository/contributions.html#looking-for-contributions).
- [X] Checking the latest version of the software to confirm it has not been fixed already.

**Comment by cenk1cenk2** [comment]
Thank you for informing. Very wierd that typedoc fails but the doc build goes through anyway.
