### ISSUE TITLE
[Support]: How to use node-schedule?

### ISSUE THREAD

**Issue by cdwmhcc** [listr2/listr2#696]
### Support Request

``` ts
let rule = new schedule.RecurrenceRule()
let job = schedule.scheduleJob("*/5 * * * * *", async () => {
      try {
          // something
          task.output = "success!"
      } catch (e) {
          console.log(e)
      }
})
task.output = "finished!"
```

but: 

``` ts
TypeError: Cannot read properties of undefined (reading 'write')
    at EventEmitter.<anonymous> (e:/package/node_modules/.pnpm/listr2@7.0.2/node_modules/listr2/dist/index.js:990:40)

```

### Preflight

- [X] Read/Search existing issues and the provided [documentation](https://listr2.kilic.dev).

**Comment by cenk1cenk2** [comment]
Hey @cdwmhcc,

We have to somehow keep the task alive until this scheduled job finishes. 

`schedule.scheduleJob` is a event emitter in this case which decouples from the current context. I am not sure how to use that specific library and await for the job itself, but i think it is not by design.

You can inside the task give a try to keep the task alive. Something like:
```typescript
const rule = new schedule.RecurrenceRule()
const job = schedule.scheduleJob("*/5 * * * * *", async () => {
      try {
          // something
          task.output = "success!"
      } catch (e) {
          console.log(e)
      }
})
task.output = "finished!"
await new Promise()
```

**Comment by cdwmhcc** [comment]
> Hey @cdwmhcc,
> 
> We have to somehow keep the task alive until this scheduled job finishes.
> 
> `schedule.scheduleJob` is a event emitter in this case which decouples from the current context. I am not sure how to use that specific library and await for the job itself, but i think it is not by design.
> 
> You can inside the task give a try to keep the task alive. Something like:
> 
> ```ts
> const rule = new schedule.RecurrenceRule()
> const job = schedule.scheduleJob("*/5 * * * * *", async () => {
>       try {
>           // something
>           task.output = "success!"
>       } catch (e) {
>           console.log(e)
>       }
> })
> task.output = "finished!"
> await new Promise()
> ```

Thank you for your quick reply and hard work, listr2 works great!

It would be even better if there was a timer/loop built in!
