### ISSUE TITLE
[Support]: How to handle nested listr2

### ISSUE THREAD

**Issue by cdwmhcc** [listr2/listr2#697]
## task1.ts

``` ts
export const task1 = async (): Promise<void> => {
  const tasks = new Listr<Ctx>([
    {
      title: 'This task1',
      task: async (ctx): Promise<void> => {
        // perform some operations
      },
    },
    ...
  ])
  try {
    await tasks.run()
  } catch (e) {
    console.error(e)
  }
}
```

## task2.ts

``` ts
import {task1} from './task1'
const task2 = async (): Promise<void> => {
  const tasks = new Listr<Ctx>([
    {
      title: 'This task2',
      task: async (ctx): Promise<void> => {
           await task1()
      },
    },
    ...
  ])
  try {
    await tasks.run()
  } catch (e) {
    console.error(e)
  }
}
```

If listr2 is nested, the nested one will not print information during execution.How should I set it up.

### Preflight

- [X] Read/Search existing issues and the provided [documentation](https://listr2.kilic.dev).

**Comment by cenk1cenk2** [comment]
Hello again @cdwmhcc,

Unfortunetely do to some stateful operations going on it it is not possible to directly pass a Listr as a subtask.

But you can use the `task.newListr` that is inside the task object to create a new one. Please read the documentation on this [here](https://listr2.kilic.dev/task/subtasks.html).

**Comment by cdwmhcc** [comment]
> Hello again @cdwmhcc,
> 
> Unfortunetely due to some stateful operations going on it it is not possible to directly pass a Listr as a subtask.
> 
> But you can use the `task.newListr` that is inside the task object to create a new one. Please read the documentation on this [here](https://listr2.kilic.dev/task/subtasks.html).
> 
> In your case where you might need to have multiple tasks on multiple files is a little bit different. https://listr2.kilic.dev/listr/manager.html can be used to create a shared task list then expanded but there is no direct examples on that.

Before submitting the issue, I read the document you posted almost word for word.

I can only say that this is a personalized requirement that belongs to me, because my project does not completely rely on listr2, but it has a certain degree of coupling.

Haha, I will think of other ways to hook it.

**Comment by cenk1cenk2** [comment]
That is okay. In a situation like this I would generate the task list first then run it or run them one after the other if it is possible.

Unfornetely since it takes control of the stdout, there can only be one instance running at a given time.
