### ISSUE TITLE
[Bug]: SimpleRenderer should not invoke process.release

### ISSUE THREAD

**Issue by jurijzahn8019** [listr2/listr2#700]
### Replication of the Problem

Run a listr job, which outputs everything to stderr.
Write to stdout anything and pipe stdout into a file (>)

Result: file will contain `ANSI_ESCAPE_CODES.CURSOR_SHOW` prepending the payload

### Problem

I have multiple commands in my cli which ouput some stuff to stderr, 
and the described above causes the usefull data to contain ansi escapes which
must be then somehow removed from it.

i suggest to remove release call in

https://github.com/listr2/listr2/blob/85d175658136647fffcaa8abfc6d5cfbedb201df/packages/listr2/src/renderer/simple/renderer.ts#L52

since simple renderer also does not call highjack on start

And this renderer generally has no problem with stdout output

### Environment

linux
node20
latest

### Preflight

- [X] Read/Search existing issues and the provided [documentation](https://listr2.kilic.dev).
- [X] Be sure to not open an issue in the [looking for contributions section](/repository/contributions.html#looking-for-contributions).
- [X] Checking the latest version of the software to confirm it has not been fixed already.

**Comment by cenk1cenk2** [comment]
Thank you very much for reporting this, this had slipped through while refactoring.
