### ISSUE TITLE
[Bug]: Doc site broken

### ISSUE THREAD

**Issue by gordonmleigh** [listr2/listr2#705]
### Replication of the Problem

1. Visit https://listr2.kilic.dev/api/
2. See 404 page

Bonus: the link in the second checkbox in the "Preflight" section of this bug form is also broken

### Problem

The API section appears to be missing. See also #688.

### Environment

Chrome 120 MacOS

### Log Output

```bash
n/a
```

### Preflight

- [X] Read/Search existing issues and the provided [documentation](https://listr2.kilic.dev).
- [X] Be sure to not open an issue in the [looking for contributions section](/repository/contributions.html#looking-for-contributions).
- [X] Checking the latest version of the software to confirm it has not been fixed already.

**Comment by cenk1cenk2** [comment]
Dear @gordonmleigh,

Thank you for reporting this, lately my build servers are not working up to task so a change in a dependency version has caused this.
