### ISSUE TITLE
[Bug]: `rxjs` is imported in the exported typescript definition but is declared as a dev dependency

### ISSUE THREAD

**Issue by fire332** [listr2/listr2#707]
### Problem

rxjs is used as a type-only import here: https://github.com/listr2/listr2/blob/365da3cbd79241051633e074bd6d075b9553673f/packages/listr2/src/interfaces/task.interface.ts#L1

But `Observable` makes it into the final typescript definition, forcing users of listr2 to have `skipLibCheck: true` in their `tsconfig.json`s or there will be this error when importing listr2:
```log
error TS2307: Cannot find module 'rxjs' or its corresponding type declarations
```

Using the `Observable` type from `rxjs` doesn't look correct as listr2 uses [its own `isObservable` function](https://github.com/listr2/listr2/blob/365da3cbd79241051633e074bd6d075b9553673f/packages/listr2/src/utils/environment/is-observable.ts#L5) instead of `rxjs`'s.

I suggest exporting an `ObervableLike` interface and re-use it in `isObservable` as TypeScript supports duck typing:

**NEW** `observablelike.interface.ts`
```ts
interface ObserverLike {
  next: (value: string) => void
  complete: () => void
  error: (err: unknown) => void
}

export interface ObservableLike {
  subscribe: (observer: ObserverLike) => unknown
}
```
**CHANGED** `is-observable.ts`
```ts
import type { ObservableLike } from '@interfaces'

export function isObservable<T> (obj: any): obj is ObservableLike
```
**CHANGED** `task.interface.ts`
```ts
export type ListrTaskResult<Ctx> = string | Promise<any> | Listr<Ctx, ListrRendererValue, ListrRendererValue> | Readable | NodeJS.ReadableStream | ObservableLike
```

### Environment

Doesn't matter.

### Preflight

- [X] Read/Search existing issues and the provided [documentation](https://listr2.kilic.dev).
- [X] Be sure to not open an issue in the [looking for contributions section](/repository/contributions.html#looking-for-contributions).
- [X] Checking the latest version of the software to confirm it has not been fixed already.

**Comment by cenk1cenk2** [comment]
Dear @fire332,

Thank you for reporting this, my assumption was at somepoint it was skipping missing libraries when it is just imported as types so I have missed this.

Would you mind to do a merge request for this or should I apply your suggestion as a patch?

**Comment by fire332** [comment]
The latter is preferable if you can do so within the next week or so as I'm a bit busy lately. You may also want to give the same treatment to `NodeJS.ReadableStream` as well so this library can work with alternative runtimes like Deno or Bun.

**Comment by fire332** [comment]
I did a quick search of the listr2 package and `rxjs` can be removed in https://github.com/listr2/listr2/blob/e65b0b9a89ac69d3cdfb67041ba646302f7f3e10/packages/listr2/package.json#L82
now that it's no longer imported.

**Comment by cenk1cenk2** [comment]
It is a dev dependency for tests, so it will not get installed through the package manager.

**Comment by fire332** [comment]
Ah, I've missed that. Thanks for the prompt release.

**Comment by cenk1cenk2** [comment]
No worries, have fun!
