### ISSUE TITLE
[Bug]: Using inquirer prompting, messages seem to wrap too soon

### ISSUE THREAD

**Issue by Peter-Sparksuite** [listr2/listr2#708]
### Replication of the Problem

[Here is a replit example](https://replit.com/@peter178/ItchyImperturbableProgram) of the issue I'm seeing.

### Problem

Even though the terminal window has plenty of columns available (eg: COLUMNS=205 being reported if I make it that wide), the prompt is still wrapping so that it will fit within an 80-column wide terminal.

Can this be fixed, or is it a configuration issue of some kind?

It does not seem to affect other output that's wider than 80 columns.

### Environment

nodejs version: 20.4.x
whatever replit is using?

### Log Output

The following was obtained from the replit 'shell' tab, widening it so that `echo $COLUMNS` shows way more than 80 characters, then doing: `tsx index.ts` to run the code.

```
⠇ This is a long title to see if it too will wrap so that it fits within 80 character width or not

? This message is longer than 80 chars, but it still seems to be wrapping for 
width of 80 (Y/n)

```

### Preflight

- [X] Read/Search existing issues and the provided [documentation](https://listr2.kilic.dev).
- [X] Be sure to not open an issue in the [looking for contributions section](/repository/contributions.html#looking-for-contributions).
- [X] Checking the latest version of the software to confirm it has not been fixed already.

**Comment by cenk1cenk2** [comment]
Dear @Peter-Sparksuite,

Thank you for reporting this I suppose inquirer can not find the column lenght properly due to us wrapping it inside a fake writable interface. Unfortunetely I do not have an immedeate idea for fixing this.
