### ISSUE TITLE
[Bug]: SIGINT listener added, but not removed, causing unwanted behavior

### ISSUE THREAD

**Issue by WesCossick** [listr2/listr2#709]
### Replication of the Problem

Here's a GIF demonstrating the problem using [this Replit](https://replit.com/@WesCossick/listr2-sigint-bug):

![Recording](https://github.com/listr2/listr2/assets/3850064/1deffc5e-1325-44f9-9429-ab6537f2ed06)

### Problem

A `SIGINT` listener is [being added here](https://github.com/listr2/listr2/blob/10401d5f1d0838f39ff8e768597be21743e4dfd9/packages/listr2/src/listr.ts#L103-L115), but at no point does it ever get removed. This causes two issues:

1. The first already-completed list get reprinted to stdout.
2. Any currently running lists do not have their tasks updated to a "failed" state, because the first list's `SIGINT` listener calls `process.exit(127)`.

### Environment

In the Replit, it's using Node.js v18.12.1 and `listr` v8.0.2.

### Log Output

```bash
Here's the final text from the GIF above.


~/listr2-sigint-bug$ node index.js
✖ Example task
~/listr2-sigint-bug$ node index.js
✔ Example task
⠙ Waiting for user to hit Ctrl-C...
^C✔ Example task
```
```


### Preflight

- [X] Read/Search existing issues and the provided [documentation](https://listr2.kilic.dev).
- [X] Be sure to not open an issue in the [looking for contributions section](/repository/contributions.html#looking-for-contributions).
- [X] Checking the latest version of the software to confirm it has not been fixed already.

**Comment by cenk1cenk2** [comment]
Dear @WesCossick,

Interesting find, isnt once supposed to remove this: https://nodejs.org/api/events.html#emitteronceeventname-listener

**Comment by WesCossick** [comment]
Only _after_ it's been called one time. So, if a user hit `Ctrl-C` multiple times in rapid succession, Node.js would only call the `SIGINT` listener once if `process.once()` is used instead of `process.on()`.

**Comment by WesCossick** [comment]
What Listr2 should be doing is calling [`process.removeListener()`](https://nodejs.org/api/events.html#emitterremovelistenereventname-listener) once a task list is done running. That will remove the listener so that Node.js doesn't call it when `SIGINT` is received.

**Comment by WesCossick** [comment]
Hey @cenk1cenk2, I just took a look at the fix implemented in 759709921cea1a1816ec50a7f1576fcb361fc294, and I'm concerned by the use of `process.removeAllListeners('SIGINT')`. I believe this will end up removing all `SIGINT` listeners, including those added by other code/packages, rather than just the `SIGINT` listeners that Listr2 is responsible for.

Did you consider using `process.removeListener()` instead?

**Comment by cenk1cenk2** [comment]
Yeah, that was not working as expected. I had the same concern but did not think over it too much. But you are definetely right.

**Comment by WesCossick** [comment]
It could be... Binding `this` makes it more complicated. I'm not sure if that would affect Node's ability to determine which listener you were trying to remove using `process.removeListener()`.

**Comment by cenk1cenk2** [comment]
Yeah, I have given an another try but again it did not work out as expected, if you have any suggestions I am pretty open to fixing it.

**Comment by WesCossick** [comment]
Let me take a look...
