### ISSUE TITLE
[Bug]: wrong ReturnType of createWritable

### ISSUE THREAD

**Issue by Dinhero21** [listr2/listr2#723]
### Replication of the Problem

[Playground Link](https://www.typescriptlang.org/play/?#code/PTAEGICcFMHMEsD2A7UALALhgDgZwFwgIZoCuARgHQDGiAtsADby4aQBMTLbn5ji5YHQCGraJGDZh1ANbDY0XF1YdguSNWCkM8RkuyRE1RbgC0ibdm3AA7pHgZhfaJQy4AUO-h1siSBlAAb1AAdXtHZ1AAX1AAM0M6UAByFWhhOiSvHz8AjABPbGgg0PDoAGU2NMSY+PpkrDzM92AAKlBuYWRyUkZ22GQ-IuRoAA8AluB3Ud9-ONJkah0UUGoYYQxoMIcnRiKACmpyfFADsmQZY5V4ZFgASlAAXgA+UAA3RHgAE1vjgDlET7QABSZUoWwiuwqa0SgXcoBWKFYoDs20iD1AwxsJVRuz2t088IA3HsURCiqJsRsoVVbpRDDZcI9QABJZCxa4OPJw0DE0k7cmM8HlSrpWm0RikOjIRno1ns5CcgnI8L8yikoro07zC6gABCpFisXEoAAPqArjcfqByIhELtOo8XrD4fDDlrzq5EFDrrA8fjufCYBhSJBUGxSNBuVElUGQ6g+c53NHmmBwNBkJ8YAgUJ58oVQAB9JkAJWgwdDABUCtAADx56CIWIrNYbcH8p4pl0APQA-EA)
```ts
// #region https://github.com/listr2/listr2/blob/master/packages/listr2/src/utils/process-output/writable.ts

import { Writable } from 'stream'
import type { WriteStream } from 'tty'

/* istanbul ignore next */
export function createWritable (cb: (chunk: string) => void): NodeJS.WritableStream {
  const writable = new Writable()

  ;(writable as WriteStream).rows = Infinity
  ;(writable as WriteStream).columns = Infinity

  writable.write = (chunk: Buffer | string): boolean => {
    cb(chunk.toString())

    return true
  }

  return writable
}

// #endregion

type _ = ReturnType<typeof createWritable>
//   ^? type _ = NodeJS.WritableStream
```

### Problem

The `ReturnType` of `createWritable` is `NodeJS.WritableStream`, which is incorrect.
It should be [`Writable`](https://nodejs.org/docs/latest/api/stream.html#class-streamwritable), [already imported above](https://github.com/listr2/listr2/blob/b4f544ebce9582f56b2b42fdbe834d70678ce966/packages/listr2/src/utils/process-output/writable.ts#L1).

This results in a few issues, such as being unable to use `task.stdout()` in places where a `Writable` is expected.

### Environment

```
$ fastfetch
             .',;::::;,'.                 dinhero21@fedora
         .';:cccccccccccc:;,.             ----------------
      .;cccccccccccccccccccccc;.          OS: Fedora Linux 40 (KDE Plasma) x86_64
    .:cccccccccccccccccccccccccc:.        Host: X570 Phantom Gaming 4
  .;ccccccccccccc;.:dddl:.;ccccccc;.      Kernel: Linux 6.10.6-200.fc40.x86_64
 .:ccccccccccccc;OWMKOOXMWd;ccccccc:.     Uptime: 3 days, 1 hour, 12 mins
.:ccccccccccccc;KMMc;cc;xMMc;ccccccc:.    Packages: 2366 (rpm), 19 (flatpak), 3 (snap)
,cccccccccccccc;MMM.;cc;;WW:;cccccccc,    Shell: zsh 5.9
:cccccccccccccc;MMM.;cccccccccccccccc:    Display (SyncMaster): 1920x1080 @ 60 Hz in 7″ [External]
:ccccccc;oxOOOo;MMM000k.;cccccccccccc:    DE: KDE Plasma 6.1.4
cccccc;0MMKxdd:;MMMkddc.;cccccccccccc;    WM: KWin (Wayland)
ccccc;XMO';cccc;MMM.;cccccccccccccccc'    WM Theme: Breeze
ccccc;MMo;ccccc;MMW.;ccccccccccccccc;     Theme: Breeze (Dark) [Qt], Breeze [GTK3]
ccccc;0MNc.ccc.xMMd;ccccccccccccccc;      Icons: breeze-dark [Qt], breeze-dark [GTK3/4]
cccccc;dNMWXXXWM0:;cccccccccccccc:,       Font: Noto Sans (10pt) [Qt], Noto Sans (10pt) [GTK3/4]
cccccccc;.:odl:.;cccccccccccccc:,.        Cursor: breeze (24px)
ccccccccccccccccccccccccccccc:'.          Terminal: konsole 24.8.0
:ccccccccccccccccccccccc:;,..             Terminal Font: Monospace (10pt)
 ':cccccccccccccccc::;,.                  CPU: AMD Ryzen 7 5800X (16) @ 3.80 GHz
                                          GPU: NVIDIA GeForce RTX 4070 [Discrete]
                                          Memory: 11.89 GiB / 31.26 GiB (38%)
                                          Swap: 2.75 MiB / 8.00 GiB (0%)
                                          Disk (/): 79.64 GiB / 1.82 TiB (4%) - btrfs
                                          Local IP (enp3s0): 192.168.0.137/24
                                          Locale: en_US.UTF-8
$ nvm current
v20.16.0
$ node --version
v20.16.0
$ npm --version
10.8.1
$ cat package.json
{
  ...
  "dependencies": {
    ...
    "listr2": "^8.2.4",
    ...
  },
  ...
}
```

### Preflight

- [X] Read/Search existing issues and the provided [documentation](https://listr2.kilic.dev).
- [X] Be sure to not open an issue in the [looking for contributions section](/repository/contributions.html#looking-for-contributions).
- [X] Checking the latest version of the software to confirm it has not been fixed already.

**Comment by cenk1cenk2** [comment]
Dear @Dinhero21,

Thanks for the issue, I can migrate this on the next major version update, probably which will be when the node 18 deprecates.

**Comment by Dinhero21** [comment]
damn, that's what I call an enthusiastic bot

**Comment by cenk1cenk2** [comment]
Haha since he is a non native monorepository bot, he likes to spam.

**Comment by Dinhero21** [comment]
ah I see, different packages, I thought the webhook was being called multiple times or something
