### ISSUE TITLE
[Bug]: zen-observable isn't supported

### ISSUE THREAD

**Issue by 1999** [listr2/listr2#724]
### Replication of the Problem

```
export const foo: ListrTask = {
	title: 'Some random foo task',
	task: () =>
		new Observable((observer) => {
			observer.next('Foo');

			setTimeout(() => {
				observer.next('Bar');
			}, 2000);

			setTimeout(() => {
				console.log(observer);
				observer.complete();
			}, 10000);
		}),
};
```

### Problem

It is said that listr2 supports Observable implementations like "rxjs" or "zen-observable" but it looks like these implementations differ. Only "rxjs" is working with listr2

### Environment

osx
node 20

### Preflight

- [X] Read/Search existing issues and the provided [documentation](https://listr2.kilic.dev).
- [X] Be sure to not open an issue in the [looking for contributions section](/repository/contributions.html#looking-for-contributions).
- [X] Checking the latest version of the software to confirm it has not been fixed already.

**Comment by cenk1cenk2** [comment]
Dear @1999,

Thank you for reporting this, I did not specifically support the `zen-observable` but now it should be fixed.

A new version will publish soon.
