### ISSUE TITLE
[Bug]: Peer dependency bump hasn't been released

### ISSUE THREAD

**Issue by jkrems** [listr2/listr2#730]
### Replication of the Problem

```sh
# In an empty directory:
npm init --yes && npm install @inquirer/prompts@7 @listr2/prompt-adapter-inquirer
```

See: https://github.com/angular/angular-cli/issues/28870

### Problem

The peer dep ranged was fixed in https://github.com/listr2/listr2/commit/e68e009ce26c6e646a93bb060029734ca295fee6 but it looks like the change never made it into a release.

### Environment

listr2: @listr2/prompt-adapter-inquirer@2.0.17 (npm latest tag)

### Log Output

```bash
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: test@1.0.0
npm error Found: @inquirer/prompts@7.1.0
npm error node_modules/@inquirer/prompts
npm error   @inquirer/prompts@"^7.1.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer @inquirer/prompts@">= 3 < 7" from @listr2/prompt-adapter-inquirer@2.0.17
```

### Preflight

- [X] Read/Search existing issues and the provided [documentation](https://listr2.kilic.dev).
- [X] Be sure to not open an issue in the [looking for contributions section](/repository/contributions.html#looking-for-contributions).
- [X] Checking the latest version of the software to confirm it has not been fixed already.

**Comment by cenk1cenk2** [comment]
Thank you for reporting this it shall be released shortly.

**Comment by cenk1cenk2** [comment]
Released with
https://gitlab.kilic.dev/libraries/listr2/-/jobs/206477
[I] [release] @listr2/prompt-adapter-inquirer
[I] [release] v2.0.18

**Comment by jkrems** [comment]
Thanks for the super quick fix!
